theme: jekyll-theme-minimal
title: Computing Stuff 
email: jesus.ferreira@gmail.com
description: This is the blog and personal web page of Jesus Ferreira, mostly about programming and related stuff.
url: "https://jferreir.github.io" # the base hostname & protocol for your site
twitter_username: jesus_z80
github_username:  jferreir
